config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/sign_in' , to: 'devise/sessions#new' 
  get '/users/sign_up' , to: 'devise/registrations#new' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'programmers#index'
  resources :programmers , :projects
  # get 'programmers', to: 'programmers#index'
  # get 'programmers/:id', to: 'programmers#show', as: :programmer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/programmer.rb
class Programmer < ApplicationRecord
    has_many :projects , dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :programmer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @programmers = Programmer.all
  end

  def show
    @programmer = Programmer.find(params[:id])
    @projects = @programmer.projects
  end

  def new
    @programmer = Programmer.new
  end

  def create
    Programmer.create(programmer_params)
    redirect_to programmers_path
  end

  def edit
    @programmer = Programmer.find(params[:id])
  end

  def update
    programmer = Programmer.find(params[:id])
    programmer.update(programmer_params)
    redirect_to programmer_path
  end

  def destroy
    Programmer.find(params[:id]).destroy

    redirect_to programmers_path
  end

  private

  def programmer_params
    params.require(:programmer).permit(:first_name, :last_name, :phone, :email)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @programmer = Programmer.find(params[:programmer_id])
    @project = Project.new
  end

  def create
    puts params
    programmer = Programmer.find(params[:project][:programmer_id])
    Project.create(params.require(:project).permit(:name, :description, :link, :programmer_id))
    redirect_to programmer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Programarizing</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign Up' , new_user_registration_path%></li>
    <% if user_signed_in? %>
    <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
  <% if user_signed_in? %>
  <div class="alert alert-secondary alert-dismissible fade show" role="alert">
    <strong> Welcome ! </strong><%= current_user.email %>
  </div>
  <% end %>
</head>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>

</html>

app/views/programmers/_form.html.erb
<body class="text-center">
  <%= form_for @programmer do |f| %>
  <form class="new_programer">
    <div class="col-sm-3">
      <%= f.text_field :first_name , {:class => "form-control",:placeholder => "First Name"}%>
    </div>

    <div class="col-sm-3 " style="padding-top: 8px;">
      <%= f.text_field :last_name , {:class => "form-control",:placeholder => "Last Name"}%>
    </div>

    <div class="col-sm-3" style="padding-top: 8px;">
      <%= f.text_field :phone , {:class => "form-control",:placeholder => "Phone"}%>
    </div>

    <div class="col-sm-3" style="padding-top: 8px;">
      <%= f.text_field :email , {:class => "form-control",:placeholder => "Email Address"}%>
    </div>

    <div class="submit_">
      <%= f.submit "Submit" , { :class => "button btn btn-primary"}%>
    </div>
  </form>
  </div>
  <% end %>
</body>

app/views/programmers/edit.html.erb
<h4>Edit <%= @programmer.first_name %> </h4>
<%= render 'programmers/form' %>

app/views/programmers/index.html.erb
<h3>All Programmers</h3>
<body class="text-center">
  <div class="button btn btn-success">
    <%= link_to 'Add a Programmer', new_programmer_path , {:class => "link"}%>
    <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z"
        clip-rule="evenodd" />
      <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd" />
      <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd" />
    </svg>
  </div>
  <br><br>
  <div class="album py-2 justify-content-lg-center d-flex">
    <div class="container justify-content-lg-center d-flex row row-cols-3">
      <% @programmers.each do |programmer| %>
      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <h6 class="card-header"><b><%= programmer.first_name %>
            <%= programmer.last_name %>
          </b></h6>
        <div class="card-body">
          <p class="card-text">Phone : <%= programmer.phone %></p>
          <p class="card-text">Email : <%= programmer.email%></p>
          <%= link_to "Show" , programmer_path(programmer) , { :class => "button btn btn-info" }%>
          <a class="btn btn-danger" data-method="delete" href="/programmers/<%= programmer.id%>">Delete</a>
        </div>
      </div>
      <% end %>
      <div>
      </div>
</body>

app/views/programmers/new.html.erb
<h4>New programmer</h4>
<%= render 'programmers/form'%>

app/views/programmers/show.html.erb
<body class="text-center">
<div class = "info">
  <h3><b><%= @programmer.first_name %>
      <%= @programmer.last_name %>
    </b></h3>
  <strong><p>Phone : <%= @programmer.phone %></p></strong>
  <strong><p>Email : <%= @programmer.email%></p></strong>
  <div class="button btn btn-primary">
    <%=link_to "Edit", edit_programmer_path(@programmer) , {:class => "link"}%>
    <svg class="bi bi-pencil-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path
        d="M15.502 1.94a.5.5 0 010 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 01.707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 00-.121.196l-.805 2.414a.25.25 0 00.316.316l2.414-.805a.5.5 0 00.196-.12l6.813-6.814z" />
      <path fill-rule="evenodd"
        d="M1 13.5A1.5 1.5 0 002.5 15h11a1.5 1.5 0 001.5-1.5v-6a.5.5 0 00-1 0v6a.5.5 0 01-.5.5h-11a.5.5 0 01-.5-.5v-11a.5.5 0 01.5-.5H9a.5.5 0 000-1H2.5A1.5 1.5 0 001 2.5v11z"
        clip-rule="evenodd" />
    </svg>
  </div>
  </div>
  <br><br>
  <div class="button btn btn-success">
    <%= link_to "New Project", new_project_path(:programmer_id => @programmer.id) , { :class => "link"}%>
    <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z"
        clip-rule="evenodd" />
      <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd" />
      <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd" />
    </svg>
  </div>
  <br><br>
  <div class="album py-2 justify-content-lg-center d-flex">
    <div class="container justify-content-lg-center d-flex row row-cols-3">
      <% @projects.each do |project| %>
      <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
        <strong class="card-header"><%= project.name %></strong>
        <div class="card-body">
          <p class="card-text"><%= project.description%></p>
          <em><%= project.link %></em>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/projects/_form.html.erb
<body class="text-center">
	<%= form_for @project do |f| %>
	<form class="new_project">
		<div class="col-sm-3">
			<%= f.hidden_field :programmer_id, :value => @programmer.id %>
			<%= f.text_field :name , {:class => "form-control",:placeholder => "Name"}%>
		</div>
		<div class="col-sm-3" style="padding-top: 8px;">
			<%= f.text_area :description  , {:class => "form-control",:placeholder => "Description"}%>
		</div>
		<div class="col-sm-3" style="padding-top: 8px;">
			<%= f.text_field :link  , {:class => "form-control",:placeholder => "Link For Your Project"}%>
		</div>
		<div class="submit_">
			<%= f.submit "Submit" , { :class => "button btn btn-primary"}%>
		</div>
	</form>
	<% end %>
</body>

app/views/projects/new.html.erb
<h4>New Project for <%= @programmer.first_name %></h4>

<%= render 'projects/form' %>